#!/usr/bin/env python3
import sys
import output, parser

def print_help():
    print("""
        Valid command-line arguments:
        -h                : Show this help message.
        -s <name>         : prints tokens in token stream
        -p <name>         : invokes parser and reports on success or failure
        -r <name>         : prints human readable version of parser's IR
            """)

def main():
    argc = len(sys.argv)
    flag = sys.argv[1]

    if flag == '-h':
        print_help()
        return
    
    if argc == 2:
        flag = '-p'
        f_name = sys.argv[1]

    elif argc == 3:
        f_name = sys.argv[2]

    elif flag != '-s' and flag != '-p' and flag != '-r':
        print_help()
    
    if argc > 3:
        print("Too many command line arguments\n")
    try:
        input_file = open(f_name,'r')
    except:
        print ("ERROR: Could not open file '"+f_name+"'. Exiting early.")
        exit(0)

    # do some initializations

    # code elided

    if flag == '-p':
        parser.parse(input_file)
        return

    elif flag == '-r':

        # Run the code for the '-r' option

        # code elided
        return

    elif flag == '-s': 
        output.print_tokens(input_file)

        return

if __name__ == "__main__":

    main()